n10 = int(input("Enter number of Rs 10 coins : "))
n5 = int(input("Enter number of Rs 5 coins : "))
n2 = int(input("Enter number of Rs 2 coins : "))
n1 = int(input("Enter number of Rs 1 coins : "))
tot = (n10*10)+(n5*5)+(n2*2)+(n1)
print("Total amount in piggy bank = ", tot)
