print("Program to demonstrate uses of relational operators.")
n1 = float(input("Enter a number : "))
n2 = float(input("Enter another number : "))
print("========================================================================================")
print(n1, " < ", n2, " = ", n1<n2)
print(n1, " > ", n2, " = ", n1>n2)
print(n1, " == ", n2, " = ", n1==n2)
print(n1, " != ", n2, " = ", n1!=n2)
print(n1, " <= ", n2, " = ", n1<=n2)
print(n1, " >= ", n2, " = ", n1>=n2)
