qnt = int(input("Enter the quantity of items being sold : "))
val = float(input("Enter the value of the item : "))
dis = float(input("Enter the discount percentage : "))
tax = float(input("Enter tax percentage : "))
amt = qnt*val
disc = amt*(dis/100)
damt = amt*((100-dis)/100)
tot = damt+ ((damt*tax)/100)
print("---------------BILL---------------")
print("|Quantity       : ", qnt, "           |")
print("|Price per item : ", val, "        |")
print("|--------------------------------|")
print("|Amount         : ", amt, "       |")
print("|Discount       : -", disc, "       |")
print("|--------------------------------|")
print("|Total          : ", damt, "        |")
print("|Tax            : +", (damt*tax)/100, "        |")
print("|--------------------------------|")
print("|Total Amount to be paid : ", end='')
print(round(tot, 2), "|")
print("|-Thank You, Visit Again-", "       |")
print("----------------------------------")
