num = int(input("Enter your roll number : "))
dec = float(input("Enter your weight : "))
sec = input("Enter your section : ")
name = input("Enter your name : ")
print("===============================================")
print("Roll Number = ", num)
print("Weight = ", dec)
print("Section = ", sec)
print("Name = ", name)
