e1 = int(input("Enter score in first exam (out of 100) : "))
e2 = int(input("Enter score in second exam (out of 100) : "))
s = int(input("Enter score in sports activities (out of 100) : "))
a1 = int(input("Enter score in first activity (out of 100) : "))
a2 = int(input("Enter score in second activity (out of 100) : "))
a3 = int(input("Enter score in third activity (out of 100) : "))
et = e1+e2
at = a1+a2+a3
ep = float((et/200)*100)
sp = float(s)
ap = float((at/300)*100)
fep = ep*(50/100)
fsp = s*(20/100)
fap = ap*(30/100)
print("===============RESULT===============")
print("Total percentage in examination : ", fep)
print("Total percentage in sports : ", fsp)
print("Total percentage in activies : ", fap)
print("=====================================")
print("Total Percentage : ", fep+fsp+fap)
